apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iris-model-v${MODEL_VERSION}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris-model-v${MODEL_VERSION}
  minReplicas: 2        
  maxReplicas: 10       
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
